### ISSUE TITLE
Runtime and Attribute Errors while generating user session string.

### ISSUE THREAD

**Issue by elbert505** [herrysis404/testbotllzy#1]
Hello,

While in step 3, 

> python generate_string_session.py
> Enter API KEY: XX
> Enter API HASH: XXXX
> C:\Users\X\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\client\client.py:242: RuntimeWarning: coroutine 'Client.stop' was never awaited
>   self.stop()
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> Traceback (most recent call last):
>   File "generate_string_session.py", line 6, in <module>
>     print(app.export_session_string())
> AttributeError: 'coroutine' object has no attribute 'export_session_string'
> sys:1: RuntimeWarning: coroutine 'Client.start' was never awaited
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Tried couple of changes for each error, but couldn't figure out how to rectify.
Any suggestions, please?

Thank you.

**Comment by aman130-afk** [comment]
hey how to get token.pickle pls help me.. which software or utility create token.pickle.. pls sugest..
